### ISSUE TITLE
Nginx Proxy reverse

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-tss-engine#91] opened 2019-03-05 02:20 UTC
Can use tpm2-tss in nginx's reverse proxy?

**Comment by AndreasFuchsSIT** [comment] 2019-03-05 09:30
Haven't tried it, but should work.

Try ssl_certificate_key using the engine:tpm2tss:keyfile format.
see http://nginx.org/en/docs/http/ngx_http_ssl_module.html

And please tell us, if it worked or even add it to the Documentation via PR. Thanks

**Comment by roberto497** [comment] 2019-03-05 18:37
I tried and the following error occurred:
(SSL: error:80066071:tpm2-tss-engine:get_auth:**User interaction error**:26096080:engine

**I believe it is by the bug that asks the password of the key even when there is no password**

**Comment by roberto497** [comment] 2019-03-05 18:39
My configuration:

location / {
                proxy_pass https://xxxxxxxxxxxxxxxxx;
                proxy_ssl_certificate      /home/user/context/client.crt;
                proxy_ssl_certificate_key  engine:tpm2tss:0x81010003;
                proxy_ssl_verify off;
                proxy_ssl_password_file /home/user/context/password;
        }

**Comment by AndreasFuchsSIT** [comment] 2019-03-06 13:16
What happens if you try to use the same key with the openssl command line ? Does it ask you for a password as well ?
Also, persistent keys without password only work if you are running tpm2-tss 2.2.1, since there was a bug in the library on older versions.

**Comment by roberto497** [comment] 2019-03-06 14:32
I update the version from tpm2-tss, now in the log of nginx i get this error:
SSL_do_handshake() failed (SSL: error:8007306F:tpm2-tss-engine:esys_auxctx_init:Some unknown error occured. Please check tpm2tss logs) while SSL handshaking to upstream

**Comment by roberto497** [comment] 2019-03-06 14:54
I update the version from tpm2-tss, now in the log of nginx i get this error:
**ERROR:tcti:src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied**

Bug nginx run as root

**Comment by roberto497** [comment] 2019-03-06 17:20
I change the /dev/tpm0 permissions and **Works!!!**
Thanks a lot for the help

**Comment by AndreasFuchsSIT** [comment] 2019-03-08 14:04
Great news...
If you can spare the time, write up some words about getting nginx to work for the README.md file.

**Comment by roberto497** [comment] 2019-03-17 00:46
Yes, I will.

**Comment by keke8273** [comment] 2020-06-29 06:01
Hi @AndreasFuchsSIT , sorry for posting in an old issue. I am looking at the same 
**SSL: error:80066071:tpm2-tss-engine:get_auth:User interaction error:26096080:engine routines:ENGINE_load_private_key:failed loading private key** when I tried to load a persistent key with no password. 

When I tried to the same with `open_ssl s_client` command, it DOES ask me to enter the password. Since there was no password set when the key is created I just press enter and everything works as expected. 

1. Does it meant I have been looking at the same bug you mentioned before? 

2. My tpm2tss library is built from the 2.4.x branch. Does it mean the fix is not merged into the 2.4.x branch? 

It has not been an issue until I try to integrate tpm with nginx. 

My nginx configs are as follows: 
```
ssl_certificate_key       engine:tpm2tss:0x81800001;
```
My environment configs are as follows:
```
nginx : 
openssl:
tpm2tss: build from 2.4.x branch (commit id 62758140aac33febee3772662e6c17ae072ba7c8)
```

**Comment by keke8273** [comment] 2020-06-29 12:30
Thanks to your reply in #156. I solved the private_key loading issue. Now nginx does start up after creating a key with `noda` attribute and no passphase. 

Now when I try to connect to the service via https, the browser is hanging and eventually timingout. Looking into the nginx error log, I found the following errors:

```
** (process:54885): CRITICAL **: 22:19:01.293: failed to allocate dbus proxy object: Timeout was reached
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7fb6e0dda0a0 failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
ERROR:tcti:src/tss2-tcti/tcti-device.c:478:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: No or directory
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7fb6dd78cd60 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
ERROR:tcti:src/tss2-tcti/tcti-device.c:478:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpm0: No sr directory
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7fb6dd78cd60 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
```

**Comment by keke8273** [comment] 2020-06-30 02:57
Upon further investigation by turning on debug log for both `tpm2-abrmd` and `tpm2-tss` library

```
sudo -u tss G_MESSAGES_DEBUG=all tpm2-abrmd --tcti=mssim
TSS2_LOG=all+trace nginx -g 'daemon off;'
```
I was found that the nginx worker process was trying to initial a null config as show below. It is somehow not affecting the nginx master process to access the private key on start. As I start the nginx process, various TPM commands are logged in the `tpm2-abrmd` process

**Comment by keke8273** [comment] 2020-06-30 03:58
based on #160, i created a file '/etc/ssl/myopenssl.cnf' with the following content:

```
openssl_conf = openssl_init

[openssl_init]
engines = engine_section
[engine_section]
tpm2tss = tpm2tss_section
[tpm2tss_section]
engine_id = tpm2tss
dynamic_path = /usr/lib/x86_64-linux-gnu/engines-1.1/libtpm2tss.so
default_algorithms = RSA
init = 1
SET_TCTI = tabrmd:bus_name=com.intel.tss2.Tabrmd
#SET_OWNERAUTH=owner123
#SET_PARENTAUTH =""

[req]
distinguished_name = subject

[subject]
```

**Comment by AndreasFuchsSIT** [comment] 2020-07-13 15:02
Sorry, I had a few days off.

That's weird though.
Have you tried different versions of tpm2-abrmd ? Seems like the error might be there ?

**Comment by keke8273** [comment] 2020-07-26 08:56
Hi @AndreasFuchsSIT  not a problem. Indeed the problem is with `tmp2-abrmd`. According to [this issue](https://github.com/tpm2-software/tpm2-abrmd/issues/529) and [this issue](https://github.com/tpm2-software/tpm2-abrmd/issues/541), there isnt a solution yet. The only workaround is use the resource manager in kernel. 

On a separate note, what is the correct way to pass password of the private key to `tpm2-tss-engine` (my keys are password protected)? 

I tried use the `ssl_password_file` config from the [ngx_http_ssl_module](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_password_file). But it didnt work. Nginx only use the password in the file when the key is provided as a file. When the key is specified in the engine form, the password is not used. 

After doing some debugging, the `ui_method` in `get_auth` method below is a nullpoint at runtime.
```
 72 static int
 73 get_auth(const char *prompt_info, UI_METHOD *ui_method, void *cb_data,
 74          TPM2B_AUTH *auth)
```

I hacked my way through it. But I still want to know if there is a better way to pass the password.

**Comment by AndreasFuchsSIT** [comment] 2020-07-27 08:36
That's quite unfortunate. No idea.
Might be worthy asking nginx why they do this or if there's a magic option missing.

**Comment by AndreasFuchsSIT** [comment] 2020-11-24 13:44
I'll close this since the final issue is with nginx

**Closed by AndreasFuchsSIT** 2020-11-24 13:44 UTC
Labels: question

**Comment by simonetolotti** [comment] 2020-12-04 16:06
Hi,
I have a private key and corresponding certificate from CA and I'd like insert private key on TPM.

I did the following:

```
tpm2_createprimary -C o -g sha256 -G rsa -c primary.ctx
tpm2_import -C primary.ctx -G rsa -i myKEY.pem -u key.pub -r key.prv
tpm2_load -C primary.ctx -u key.pub -r key.prv -c key.ctx
tpm2_evictcontrol -C o -c key.ctx 0x81010002
```

and  my Nginx is the following:

```
https
server {
    listen 443 ssl;
    root /var/www/localhost/html;
    index index.html index.htm;
    server_name myhome.it;
    ssl_certificate /etc/ssl/certs/myhome.it.crt;
    ssl_certificate_key engine:tpm2tss:0x81010002;
    
   error_page 500 502 503 504 /50x.html;
}
```

And  I have the issue:

> nginx: [emerg] cannot load certificate key "engine:tpm2tss:0x81010002": ENGINE_load_private_key() failed (SSL: error:80066071:tpm2-tss-engine:get_auth:User interaction error:26096080:engine routines:ENGINE_load_private_key:failed loading private key)
> nginx: configuration file /etc/nginx/nginx.conf test failed

Of course, If I use directly access to private key, Nginx works good !

`ssl_certificate_key /etc/ssl/private/myKEY.pem;`

Also, when I create a self-signed certificate, I don't have any issues: 

```
tpm2tss-genkey /etc/ssl/private/mykey.pem
openssl req -new -x509 -engine tpm2tss -key /etc/ssl/private/mykey.pem -keyform engine -out /etc/ssl/certs/mykey.crt
```

```
server {
    listen 443 ssl;
    root /var/www/html;

    index index.html index.htm;
    server_name myhome.it;

    ssl_certificate /etc/ssl/certs/myhome.it.crt;
    ssl_certificate_key engine:tpm2tss:/etc/ssl/private/myKEY.pem;

    # redirect server error pages to the static page /50x.html
    error_page 500 502 503 504 /50x.html;

    location / {
        try_files $uri  $uri/ /index.html;
    }
}
```

is there a my wrong or it is a Nginx bug ?

Thanks,

**Comment by AndreasFuchsSIT** [comment] 2020-12-04 16:12
For a persistent key (0x81xxxxxx) the tpm2-tss-engine cannot know if it has a password or not (i.e. an empty password). That's why it wants to ask the user for the password (in order to not trigger the TPM's anti-bruteforce feature). nginx does not offer a "ask user" function and that's the reason for the error.

Please try to set the noda flag for your key. This will disable the TPM's anti-bruteforce feature and then the engine will attempt to authenticate to the key with an empty password before asking the user for input.

Also see this test: https://github.com/tpm2-software/tpm2-tss-engine/blob/master/test/rsasign_persistent_emptyauth.sh

**Comment by simonetolotti** [comment] 2020-12-05 11:34
Thanks Andreas, 
How can I set the "noda" ? I tried to add "--attributes noda"  to both tpm2_createprimary  and tpm2_import but they don't accept that flag.

Sorry but I'm new on TPM...

**Comment by simonetolotti** [comment] 2020-12-05 11:47
I'm using Yocto and the following recipes version:

tpm2-tss_2.3.2.bb
tpm2-tools_4.1.1.bb
