### ISSUE TITLE
Embedded Linux, buildroot with autoconf

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-tss-engine#150] opened 2019-11-14 14:07 UTC
I'm working on an embedded Linux project with a quad-core x86_64 CPU.

In Buildroot, there is already the packages:
BR2_PACKAGE_TPM2_TSS
BR2_PACKAGE_TPM2_TOOLS

And so now I'm trying to add in:

BR2_PACKAGE_TPM2_TSS_ENGINE

Buildroot is pretty streamlined for adding packages that use 'autoconf',  but for some reason it isn't working with tpm2-tss-engine. When it tries to build, it fails with an error to do with it having the wrong "staging" or "target" directory. I've been troubleshooting this for a few days now. The strange thing is that when tpm2-tss-engine fails to build, it disrupts the entire build system and then nothing will build after that. The package "tpm2-tss" builds just fine even though they seem to use autoconf very similarly.

I think I might have to configure the tpm2-tss-engine package by myself first, and then turn it into a "generic" package that simply has a Makefile.

Anyone been at this before?

**Comment by AndreasFuchsSIT** [comment] 2019-11-14 14:43
It should build pretty much that same way as all other other things from tpm2-software.
Maybe have a look at https://git.buildroot.net/buildroot/tree/package/tpm2-totp/tpm2-totp.mk for a blueprint.
The only difference is that we install to the openssl engines dir (as reported by pkg-config).
Look at the enginesdir variable inside libcrypto.pc
Or try to set it manually with ./configure --with-enginesdir

Otherwise, a build-log would be helpful..... ;-)

**Comment by jhealyt** [comment] 2019-11-15 10:44
I gave up on using the 'autoconf' stuff that comes bundled in the archive "tpm2-tss-engine-1.0.1.tar.gz".

Even if I were to get it working properly by using "--with-enginesdir", I still don't like the idea that one package is able to screw up my entire build system in such a way that I can't build anything else afterward.

So here's what I did:
(1) I ran ./configure
(2) I ran make SHELL='sh -x' so that I can see every command
(3) I took the output from 2 and grep'ed to find invocations of gcc
(4) I collected all of these gcc invocations and put them together in a Makefile

So here's what I've got:
`################################################################################
#
# tpm2-tss-engine
#
################################################################################

TPM2_TSS_ENGINE_VERSION = 1.0.1
TPM2_TSS_ENGINE_SOURCE = tpm2-tss-engine-$(TPM2_TSS_ENGINE_VERSION).tar.gz
TPM2_TSS_ENGINE_SITE = $(TOPDIR)/board/xyz/dynamo/distfiles
TPM2_TSS_ENGINE_SITE_METHOD = file
TPM2_TSS_ENGINE_LICENSE = BSD-2-Clause
TPM2_TSS_ENGINE_LICENSE_FILES = LICENSE
TPM2_TSS_ENGINE_INSTALL_STAGING = NO
TPM2_TSS_ENGINE_INSTALL_TARGET = YES
TPM2_TSS_ENGINE_INSTALL_HOST = NO
TPM2_TSS_ENGINE_DEPENDENCIES = tpm2-tss
TPM2_TSS_ENGINE_PATCH_DIR = $(TOPDIR)/board/xyz/dynamo/patches/tpm2-tss-engine

XYZ_CPPFLAGS = -DPACKAGE_NAME="tpm2-tss-engine" -DPACKAGE_TARNAME="tpm2-tss-engine" -DPACKAGE_VERSION="$(TPM2_TSS_ENGINE_VERSION)" \
               -DPACKAGE_STRING="tpm2-tss-engine $(TPM2_TSS_ENGINE_VERSION)" -DPACKAGE_BUGREPORT="https://github.com/tpm2-software/tpm2-tss-engine/issues" \
               -DPACKAGE_URL="https://github.com/tpm2-software/tpm2-tss-engine" -DPACKAGE="tpm2-tss-engine" -DVERSION="$(TPM2_TSS_ENGINE_VERSION)" \
               -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 \
               -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR="$(@D)/" -DPIC \
               -I$(@D)/include
		   
XYZ_CFLAGS = -std=c99 -fPIC -fstack-protector-all \
             -Wall -Wextra -Wformat-security -Wno-missing-braces
		 
XYZ_SRC = $(@D)/src

XYZ_PATH_TO_DYNAMICS = $(TOPDIR)/output/target/usr/lib

XYZ_VERSION_SCRIPT = "{ global: bind_engine; tpm2tss_ecc_genkey; tpm2tss_ecc_getappdata; tpm2tss_ecc_makekey; \
                        tpm2tss_ecc_setappdata; tpm2tss_rsa_genkey; tpm2tss_rsa_makekey; tpm2tss_tpm2data_read; \
                        tpm2tss_tpm2data_readtpm; tpm2tss_tpm2data_write; v_check; local: *; };"

define TPM2_TSS_ENGINE_BUILD_CMDS

	gcc $(XYZ_CPPFLAGS) $(XYZ_CFLAGS) -c $(XYZ_SRC)/tpm2-tss-engine.c -o $(@D)/libtpm2tss_la-tpm2-tss-engine.o
	gcc $(XYZ_CPPFLAGS) $(XYZ_CFLAGS) -c $(XYZ_SRC)/tpm2-tss-engine-common.c -o $(@D)/libtpm2tss_la-tpm2-tss-engine-common.o
	gcc $(XYZ_CPPFLAGS) $(XYZ_CFLAGS) -c $(XYZ_SRC)/tpm2-tss-engine-tcti.c -o $(@D)/libtpm2tss_la-tpm2-tss-engine-tcti.o
	gcc $(XYZ_CPPFLAGS) $(XYZ_CFLAGS) -c $(XYZ_SRC)/tpm2-tss-engine-err.c -o $(@D)/libtpm2tss_la-tpm2-tss-engine-err.o
	gcc $(XYZ_CPPFLAGS) $(XYZ_CFLAGS) -c $(XYZ_SRC)/tpm2-tss-engine-ecc.c -o $(@D)/libtpm2tss_la-tpm2-tss-engine-ecc.o
	gcc $(XYZ_CPPFLAGS) $(XYZ_CFLAGS) -c $(XYZ_SRC)/tpm2-tss-engine-rand.c -o $(@D)/libtpm2tss_la-tpm2-tss-engine-rand.o
	gcc $(XYZ_CPPFLAGS) $(XYZ_CFLAGS) -c $(XYZ_SRC)/tpm2-tss-engine-rsa.c -o $(@D)/libtpm2tss_la-tpm2-tss-engine-rsa.o

	# We need to create the version script file to pass to the linker
	echo $(XYZ_VERSION_SCRIPT) > $(@D)/lib_dont_explicitly_load_tpm2tss.ver
	
	gcc -DPIC -shared -fPIC  \
	$(@D)/libtpm2tss_la-tpm2-tss-engine.o \
	$(@D)/libtpm2tss_la-tpm2-tss-engine-common.o \
	$(@D)/libtpm2tss_la-tpm2-tss-engine-tcti.o \
	$(@D)/libtpm2tss_la-tpm2-tss-engine-err.o \
	$(@D)/libtpm2tss_la-tpm2-tss-engine-ecc.o \
	$(@D)/libtpm2tss_la-tpm2-tss-engine-rand.o \
	$(@D)/libtpm2tss_la-tpm2-tss-engine-rsa.o \
	$(XYZ_PATH_TO_DYNAMICS)/libtss2-esys.so \
	$(XYZ_PATH_TO_DYNAMICS)/libtss2-sys.so \
	$(XYZ_PATH_TO_DYNAMICS)/libtss2-mu.so \
	-lcrypto -ldl \
	-fstack-protector-all \
	-Wl,--no-undefined -Wl,-z -Wl,noexecstack -Wl,-z -Wl,now -Wl,-z -Wl,relro -Wl,-soname -Wl,lib_dont_explicitly_load_tpm2tss.so \
	-Wl,-version-script -Wl,$(@D)/lib_dont_explicitly_load_tpm2tss.ver \
	-o $(@D)/lib_dont_explicitly_load_tpm2tss.so

	# The linker flags three lines above are: --no-undefined -z noexecstack -z now -z relro -soname lib_dont_explicitly_load_tpm2tss.so
	#                                         -version-script $(@D)/lib_dont_explicitly_load_tpm2tss.ver
		
	# After the dynamic shared library is built, the next part is to make the key generator binary tpm2tss-genkey

	gcc $(XYZ_CPPFLAGS) $(XYZ_CFLAGS) -c $(XYZ_SRC)/tpm2tss-genkey.c -o $(@D)/tpm2tss_genkey-tpm2tss-genkey.o

	gcc -std=c99 -Wall -Wextra -Wformat-security -fstack-protector-all -fPIC -Wno-missing-braces \
	    -Wl,--no-undefined -Wl,-z -Wl,noexecstack -Wl,-z -Wl,now -Wl,-z -Wl,relro \
	    -o $(@D)/tpm2tss-genkey \
	    $(@D)/tpm2tss_genkey-tpm2tss-genkey.o \
	    $(XYZ_PATH_TO_DYNAMICS)/libtss2-tcti-mssim.so \
	    $(XYZ_PATH_TO_DYNAMICS)/libtss2-tcti-device.so \
	    $(XYZ_PATH_TO_DYNAMICS)/libtss2-esys.so \
	    $(XYZ_PATH_TO_DYNAMICS)/libtss2-sys.so \
	    $(XYZ_PATH_TO_DYNAMICS)/libtss2-mu.so \
	    -lcrypto -ldl \
	    $(@D)/lib_dont_explicitly_load_tpm2tss.so \
	    -Wl,-rpath -Wl,/usr/lib
	    
	    # The linker flags twelve lines above are: --no-undefined -z noexecstack -z now -z relro
	    # The linker flags three lines above are: -rpath /usr/lib
endef

define TPM2_TSS_ENGINE_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/lib_dont_explicitly_load_tpm2tss.so $(TARGET_DIR)/usr/lib
	$(INSTALL) -D -m 0755 $(@D)/tpm2tss-genkey $(TARGET_DIR)/usr/bin
	
	# Also make a symbolic link in /usr/lib/engine-1.1
	mkdir -p $(TARGET_DIR)/usr/lib/engines-1.1
	ln -sf ../lib_dont_explicitly_load_tpm2tss.so $(TARGET_DIR)/usr/lib/engines-1.1/lib_dont_explicitly_load_tpm2tss.so
endef

$(eval $(generic-package))`

**Comment by AndreasFuchsSIT** [comment] 2019-11-15 11:09
Sounds like effectively you just override the `make install` directives.
I guess setting enginesdir or fixing libcrypto.pc from openssl would've been easier but it works, so hey.
Just mind that future updates might add or remove files and build flags.

**Comment by jhealyt** [comment] 2019-11-15 11:13
There isn't anything about the installation folders for libopenssl or any of the pieces of software from tpm2-software that makes it okay for the 'autoconf' for tpm2-tss-engine to totally screw up my build system so that I then have to delete a few gigs of data and then spend 13 minutes copying it all back.

I have several dozen (if not hundreds) of 'autoconf' packages in my buildroot, and the tpm2-tss-engine one is the only one that obliterates the galaxy.

**Comment by AndreasFuchsSIT** [comment] 2019-11-15 11:18
It would be great if you could specify what the "screw up" is so we can fix it.
From the little I've read is looks like a misconfigured enginesdir, but I'd need to validate this and know how this could screw up your build.

That's why I asked for some logs so we can fix the "screw up".
I'll reopen then and hope for logs or some other details.

**Comment by jhealyt** [comment] 2019-11-15 11:22
I've gotten this working by making my own ".mk" file after days of troubleshooting, and so I can move on from this now, but when I have a few minutes at the end of the day, I'll check out my old setup and rebuild it in order to get the failed build log. And I will also try to show how no other package will build after trying to build tpm2-tss-engine (meaning I have to spend 13mins copying gigs of files back over).

I'll try do this before I leave work today.

**Comment by AndreasFuchsSIT** [comment] 2019-11-15 11:24
Thanks, appreciated

**Comment by AndreasFuchsSIT** [comment] 2019-11-15 11:49
P.S. The config.log file would of course also help

**Comment by capiman2** [comment] 2020-08-24 08:07
Were there any recent updates on this? Was it solved? Changes mainlined on buildroot?

**Comment by AndreasFuchsSIT** [comment] 2020-08-24 08:14
apparently not.
But without some more information on why it's failing on buildroot compilation I cannot really help here.

**Comment by capiman2** [comment] 2020-08-24 15:54
Added locally a (smaller) way to add package, but was not yet working.
Sent question to buildroot mailing list:
http://lists.busybox.net/pipermail/buildroot/2020-August/289791.html

**Comment by AndreasFuchsSIT** [comment] 2020-11-24 13:40
I guess I'll close this issue. According to the mail thread it now hangs on AC_SUBST and AS_IF not being defined, which is not a bug in this project.
(http://lists.busybox.net/pipermail/buildroot/2020-August/289923.html)

**Closed by AndreasFuchsSIT** 2020-11-24 13:40 UTC
