### ISSUE TITLE
The engine install path should be flexible

### ISSUE THREAD

**Issue by safayetahmedatge** [tpm2-software/tpm2-tss-engine#21] opened 2018-10-11 13:51 UTC
The tpm2tss engine is installed at a fixed location, "@libdir@/openssl/engines".

https://github.com/tpm2-software/tpm2-tss-engine/blob/948a4db37767d1ece62f97c1aabae845697758a3/Makefile.am#L54

The actual engine directory is dependent on the openssl installation. In an Ubuntu 16.04 platform, it's "/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/". In an alpine environment, it's "/usr/lib/engines/". This directory should be configurable.

**Comment by AndreasFuchsSIT** [comment] 2018-10-11 15:15
But @libdir@ is replaced arroding to the distro. For Ubuntu @libdir@=/usr/lib/x86_64-linux-gnu/ and for alpine it should then be @libdir@=/usr/lib/.

Could you elaborate on what the problem is exactly ?

**Comment by safayetahmedatge** [comment] 2018-10-11 15:36
I run into the issue on Alpine. When I try to use the engine with "openssl engine -t tpm2tss", I get the error that the corresponding shared library is not found. When I explicitly load the engine, I no longer get that error.

I assumed that for Ubuntu, @libdir@=/usr/lib, not /usr/lib/x86_64-linux-gnu/. My assumption could be incorrect.

My original thinking was to add a parameter "--with-enginedir" as you suggested. However, the recommendation in https://github.com/tpm2-software/tpm2-tss-engine/issues/16 looks more appropriate. I have the same question as you about the "correct" way to do this. I need to do a little bit more research on how other projects do this.

Thank you, @AndreasFuchsSIT for your response.

**Comment by AndreasFuchsSIT** [comment] 2018-10-11 15:46
Ok, I got it.
Alping expects @libdir@/engines and Ubuntu expects @libdir@/openssl-1.0.0/engines
Weird...

So yes, I'll to #16 but also add --with-enginedir as well.

**Comment by AndreasFuchsSIT** [comment] 2018-10-12 15:36
fixed via #23

**Closed by AndreasFuchsSIT** 2018-10-12 15:36 UTC
Labels: enhancement
